// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awscnjriednkyrgpyeds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3c2NuanJpZWRua3lyZ3B5ZWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NDc5OTQsImV4cCI6MjA1MjEyMzk5NH0.azvYsSc9cXUtblvGzQ7ylYBxeihgPUvw2e55hb54B5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL.trim().replace(/\/$/, ''), // Remove any trailing slashes and whitespace
  SUPABASE_PUBLISHABLE_KEY.trim()
);